from enum import StrEnum


class LifecycleState(StrEnum):
    ACTIVE = "ACTIVE"
    DEPRECATED = "DEPRECATED"
    MERGED = "MERGED"
    RETIRED = "RETIRED"


class ApprovalState(StrEnum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"


class AliasState(StrEnum):
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class BarcodeState(StrEnum):
    PROPOSED = "PROPOSED"
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    VERIFIED_ACTIVE = "VERIFIED_ACTIVE"
    CONFLICTED = "CONFLICTED"
    REJECTED = "REJECTED"
    DEPRECATED = "DEPRECATED"
    REPLACED = "REPLACED"


class SubmissionType(StrEnum):
    NEW_PRODUCT = "NEW_PRODUCT"
    NEW_VARIANT = "NEW_VARIANT"
    ADD_BARCODE = "ADD_BARCODE"
    REMOVE_BARCODE = "REMOVE_BARCODE"
    ADD_ALIAS = "ADD_ALIAS"
    CHANGE_CANONICAL_NAME = "CHANGE_CANONICAL_NAME"
    CHANGE_BRAND = "CHANGE_BRAND"
    CHANGE_VARIANT = "CHANGE_VARIANT"
    CHANGE_CATEGORY = "CHANGE_CATEGORY"
    CORRECT_IDENTITY = "CORRECT_IDENTITY"
    POSSIBLE_DUPLICATE = "POSSIBLE_DUPLICATE"
    MERGE_IDENTITY = "MERGE_IDENTITY"
    REMAP_IDENTITY = "REMAP_IDENTITY"
    RETIRE_IDENTITY = "RETIRE_IDENTITY"


class SubmissionState(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    PENDING_REVIEW = "PENDING_REVIEW"
    NEEDS_CHANGES = "NEEDS_CHANGES"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"
    SUPERSEDED = "SUPERSEDED"


class ReviewState(StrEnum):
    OPEN = "OPEN"
    IN_REVIEW = "IN_REVIEW"
    NEEDS_MORE_INFORMATION = "NEEDS_MORE_INFORMATION"
    DECIDED = "DECIDED"
    CLOSED = "CLOSED"


class ReviewOutcome(StrEnum):
    INITIAL_OWNER_AUTHORIZED_PUBLICATION = "INITIAL_OWNER_AUTHORIZED_PUBLICATION"
    APPROVE_NEW = "APPROVE_NEW"
    MATCH_EXISTING = "MATCH_EXISTING"
    APPROVE_CORRECTION = "APPROVE_CORRECTION"
    NEEDS_MORE_INFORMATION = "NEEDS_MORE_INFORMATION"
    REJECT = "REJECT"
    WITHDRAW = "WITHDRAW"


class CoverageState(StrEnum):
    SUBMITTED_PENDING = "SUBMITTED_PENDING"
    NEEDS_MORE_INFORMATION = "NEEDS_MORE_INFORMATION"
    LINKED_APPROVED = "LINKED_APPROVED"
    REJECTED = "REJECTED"
    STALE = "STALE"
    REMAPPED = "REMAPPED"
    WITHDRAWN = "WITHDRAWN"


class ExposurePreference(StrEnum):
    HIDDEN = "HIDDEN"
    WITHIN_BUSINESS = "WITHIN_BUSINESS"
    WIDER = "WIDER"


class VisibilityScope(StrEnum):
    HIDDEN = "HIDDEN"
    WITHIN_BUSINESS_PROVISIONAL = "WITHIN_BUSINESS_PROVISIONAL"
    WITHIN_BUSINESS_TRUSTED = "WITHIN_BUSINESS_TRUSTED"
    WIDER_TRUSTED = "WIDER_TRUSTED"


class SnapshotState(StrEnum):
    CREATED = "CREATED"
    PUBLISHED = "PUBLISHED"
    SUPERSEDED = "SUPERSEDED"
    WITHDRAWN = "WITHDRAWN"


class PrincipalRole(StrEnum):
    BUSINESS = "BUSINESS"
    NTHEEMBA = "NTHEEMBA"
    REVIEWER = "REVIEWER"
    ADMIN = "ADMIN"


class RelationshipType(StrEnum):
    MERGED_INTO = "MERGED_INTO"
    REMAPPED_TO = "REMAPPED_TO"
    REPLACED_BY = "REPLACED_BY"
    RETIRED = "RETIRED"
