"""sprint 02.2 ncpc persistence

Revision ID: 11ec987dd3e6
Revises:
Create Date: 2026-09-02 12:00:55.848327
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

revision: str = '11ec987dd3e6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_clients',
    sa.Column('client_id', sa.String(length=96), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('BUSINESS', 'NTHEEMBA', 'REVIEWER', 'ADMIN', name='principalrole', native_enum=False), nullable=False),
    sa.Column('business_id', sa.String(length=128), nullable=True),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('token_digest')
    )
    op.create_index(op.f('ix_api_clients_business_id'), 'api_clients', ['business_id'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_name', sa.String(length=240), nullable=False),
    sa.Column('normalized_name', sa.String(length=240), nullable=False),
    sa.Column('lifecycle', sa.Enum('ACTIVE', 'DEPRECATED', 'MERGED', 'RETIRED', name='lifecyclestate', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_name', sa.String(length=240), nullable=False),
    sa.Column('normalized_name', sa.String(length=240), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('taxonomy_version', sa.Integer(), nullable=False),
    sa.Column('lifecycle', sa.Enum('ACTIVE', 'DEPRECATED', 'MERGED', 'RETIRED', name='lifecyclestate', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'normalized_name', name='uq_category_parent_name')
    )
    op.create_table('id_sequences',
    sa.Column('namespace', sa.String(length=16), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('namespace')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=96), nullable=False),
    sa.Column('entity_kind', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('actor_client_id', sa.String(length=96), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('old_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('new_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_client_id'], ['api_clients.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('canonical_name', sa.String(length=320), nullable=False),
    sa.Column('normalized_name', sa.String(length=320), nullable=False),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('lifecycle', sa.Enum('ACTIVE', 'DEPRECATED', 'MERGED', 'RETIRED', name='lifecyclestate', native_enum=False), nullable=False),
    sa.Column('approval_state', sa.Enum('DRAFT', 'APPROVED', name='approvalstate', native_enum=False), nullable=False),
    sa.Column('superseded_by_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(lifecycle <> 'MERGED') OR (superseded_by_id IS NOT NULL)", name='ck_product_merged_has_survivor'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_normalized_name'), 'products', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_products_public_id'), 'products', ['public_id'], unique=True)
    op.create_table('publication_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('CREATED', 'PUBLISHED', 'SUPERSEDED', 'WITHDRAWN', name='snapshotstate', native_enum=False), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=96), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['api_clients.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash'),
    sa.UniqueConstraint('version')
    )
    op.create_index(op.f('ix_publication_snapshots_public_id'), 'publication_snapshots', ['public_id'], unique=True)
    op.create_table('variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_name', sa.String(length=320), nullable=False),
    sa.Column('normalized_name', sa.String(length=320), nullable=False),
    sa.Column('pack_definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('lifecycle', sa.Enum('ACTIVE', 'DEPRECATED', 'MERGED', 'RETIRED', name='lifecyclestate', native_enum=False), nullable=False),
    sa.Column('approval_state', sa.Enum('DRAFT', 'APPROVED', name='approvalstate', native_enum=False), nullable=False),
    sa.Column('superseded_by_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(lifecycle <> 'MERGED') OR (superseded_by_id IS NOT NULL)", name='ck_variant_merged_has_survivor'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variants_normalized_name'), 'variants', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_variants_product_id'), 'variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_variants_public_id'), 'variants', ['public_id'], unique=True)
    op.create_table('aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_text', sa.String(length=320), nullable=False),
    sa.Column('normalized_text', sa.String(length=320), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('variant_id', sa.String(length=36), nullable=True),
    sa.Column('alias_kind', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('state', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='aliasstate', native_enum=False), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(product_id IS NOT NULL AND variant_id IS NULL) OR (product_id IS NULL AND variant_id IS NOT NULL)', name='ck_alias_exactly_one_target'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_text', 'product_id', 'variant_id', name='uq_alias_target_normalized')
    )
    op.create_index(op.f('ix_aliases_normalized_text'), 'aliases', ['normalized_text'], unique=False)
    op.create_table('barcode_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('variant_id', sa.String(length=36), nullable=False),
    sa.Column('original_value', sa.String(length=128), nullable=False),
    sa.Column('normalized_value', sa.String(length=128), nullable=False),
    sa.Column('symbology', sa.String(length=32), nullable=True),
    sa.Column('state', sa.Enum('PROPOSED', 'PENDING_VERIFICATION', 'VERIFIED_ACTIVE', 'CONFLICTED', 'REJECTED', 'DEPRECATED', 'REPLACED', name='barcodestate', native_enum=False), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_ref', sa.String(length=256), nullable=True),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('conflict_group_id', sa.String(length=36), nullable=True),
    sa.Column('replacement_claim_id', sa.String(length=36), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['replacement_claim_id'], ['barcode_claims.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barcode_claims_conflict_group_id'), 'barcode_claims', ['conflict_group_id'], unique=False)
    op.create_index(op.f('ix_barcode_claims_normalized_value'), 'barcode_claims', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_barcode_claims_variant_id'), 'barcode_claims', ['variant_id'], unique=False)
    op.create_index('uq_barcode_trusted_active', 'barcode_claims', ['normalized_value'], unique=True, postgresql_where=sa.text("state = 'VERIFIED_ACTIVE' AND active IS TRUE"), sqlite_where=sa.text("state = 'VERIFIED_ACTIVE' AND active IS 1"))
    op.create_table('publication_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('variant_id', sa.String(length=36), nullable=False),
    sa.Column('product_version', sa.Integer(), nullable=False),
    sa.Column('variant_version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['publication_snapshots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'variant_id', name='uq_snapshot_variant')
    )
    op.create_index(op.f('ix_publication_entries_snapshot_id'), 'publication_entries', ['snapshot_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('submission_type', sa.Enum('NEW_PRODUCT', 'NEW_VARIANT', 'ADD_BARCODE', 'REMOVE_BARCODE', 'ADD_ALIAS', 'CHANGE_CANONICAL_NAME', 'CHANGE_BRAND', 'CHANGE_VARIANT', 'CHANGE_CATEGORY', 'CORRECT_IDENTITY', 'POSSIBLE_DUPLICATE', 'MERGE_IDENTITY', 'REMAP_IDENTITY', 'RETIRE_IDENTITY', name='submissiontype', native_enum=False), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'SUBMITTED', 'PENDING_REVIEW', 'NEEDS_CHANGES', 'APPROVED', 'PUBLISHED', 'REJECTED', 'WITHDRAWN', 'SUPERSEDED', name='submissionstate', native_enum=False), nullable=False),
    sa.Column('business_id', sa.String(length=128), nullable=True),
    sa.Column('business_product_ref', sa.String(length=128), nullable=True),
    sa.Column('target_product_id', sa.String(length=36), nullable=True),
    sa.Column('target_variant_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('submitter_client_id', sa.String(length=96), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('previous_submission_id', sa.String(length=36), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['previous_submission_id'], ['submissions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitter_client_id'], ['api_clients.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_variant_id'], ['variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submitter_client_id', 'idempotency_key', name='uq_submission_client_idempotency')
    )
    op.create_index(op.f('ix_submissions_business_id'), 'submissions', ['business_id'], unique=False)
    op.create_index(op.f('ix_submissions_business_product_ref'), 'submissions', ['business_product_ref'], unique=False)
    op.create_index(op.f('ix_submissions_public_id'), 'submissions', ['public_id'], unique=True)
    op.create_index(op.f('ix_submissions_submitter_client_id'), 'submissions', ['submitter_client_id'], unique=False)
    op.create_table('business_coverages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=128), nullable=False),
    sa.Column('business_product_ref', sa.String(length=128), nullable=False),
    sa.Column('shop_id', sa.String(length=128), nullable=True),
    sa.Column('variant_id', sa.String(length=36), nullable=True),
    sa.Column('submission_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.Enum('SUBMITTED_PENDING', 'NEEDS_MORE_INFORMATION', 'LINKED_APPROVED', 'REJECTED', 'STALE', 'REMAPPED', 'WITHDRAWN', name='coveragestate', native_enum=False), nullable=False),
    sa.Column('exposure_preference', sa.Enum('HIDDEN', 'WITHIN_BUSINESS', 'WIDER', name='exposurepreference', native_enum=False), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('location_projection', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('first_linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('variant_id IS NOT NULL OR submission_id IS NOT NULL', name='ck_coverage_variant_or_submission'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_coverages_business_id'), 'business_coverages', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_coverages_shop_id'), 'business_coverages', ['shop_id'], unique=False)
    op.create_index(op.f('ix_business_coverages_submission_id'), 'business_coverages', ['submission_id'], unique=False)
    op.create_index('uq_coverage_active_business_product', 'business_coverages', ['business_id', 'business_product_ref'], unique=True, postgresql_where=sa.text('active IS TRUE'), sqlite_where=sa.text('active IS 1'))
    op.create_table('proposed_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('field_path', sa.String(length=160), nullable=False),
    sa.Column('old_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('proposed_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposed_changes_submission_id'), 'proposed_changes', ['submission_id'], unique=False)
    op.create_table('review_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'IN_REVIEW', 'NEEDS_MORE_INFORMATION', 'DECIDED', 'CLOSED', name='reviewstate', native_enum=False), nullable=False),
    sa.Column('assigned_to', sa.String(length=96), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['api_clients.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_cases_public_id'), 'review_cases', ['public_id'], unique=True)
    op.create_index(op.f('ix_review_cases_submission_id'), 'review_cases', ['submission_id'], unique=True)
    op.create_table('review_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_case_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_client_id', sa.String(length=96), nullable=False),
    sa.Column('outcome', sa.Enum('APPROVE_NEW', 'MATCH_EXISTING', 'APPROVE_CORRECTION', 'NEEDS_MORE_INFORMATION', 'REJECT', 'WITHDRAW', name='reviewoutcome', native_enum=False), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('decision_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_case_id'], ['review_cases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_client_id'], ['api_clients.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_review_case_id'), 'review_decisions', ['review_case_id'], unique=False)
    op.create_table('identity_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_kind', sa.String(length=16), nullable=False),
    sa.Column('source_product_id', sa.String(length=36), nullable=True),
    sa.Column('target_product_id', sa.String(length=36), nullable=True),
    sa.Column('source_variant_id', sa.String(length=36), nullable=True),
    sa.Column('target_variant_id', sa.String(length=36), nullable=True),
    sa.Column('relationship_type', sa.Enum('MERGED_INTO', 'REMAPPED_TO', 'REPLACED_BY', 'RETIRED', name='relationshiptype', native_enum=False), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(entity_kind = 'PRODUCT' AND source_product_id IS NOT NULL AND target_product_id IS NOT NULL AND source_variant_id IS NULL AND target_variant_id IS NULL) OR (entity_kind = 'VARIANT' AND source_variant_id IS NOT NULL AND target_variant_id IS NOT NULL AND source_product_id IS NULL AND target_product_id IS NULL)", name='ck_identity_relationship_kind'),
    sa.ForeignKeyConstraint(['decision_id'], ['review_decisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_variant_id'], ['variants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_variant_id'], ['variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("""
        CREATE FUNCTION ncpc_protect_released_snapshot() RETURNS trigger AS $$
        BEGIN
          IF TG_OP = 'DELETE' AND OLD.state IN ('PUBLISHED', 'SUPERSEDED', 'WITHDRAWN') THEN
            RAISE EXCEPTION 'released snapshots cannot be deleted';
          END IF;
          IF TG_OP = 'UPDATE' AND OLD.state IN ('PUBLISHED', 'SUPERSEDED', 'WITHDRAWN') THEN
            IF NEW.public_id <> OLD.public_id OR NEW.version <> OLD.version
               OR NEW.content_hash <> OLD.content_hash OR NEW.item_count <> OLD.item_count
               OR NEW.created_by <> OLD.created_by OR NEW.created_at <> OLD.created_at
               OR NEW.published_at IS DISTINCT FROM OLD.published_at THEN
              RAISE EXCEPTION 'released snapshot content and metadata are immutable';
            END IF;
            IF NEW.state NOT IN ('SUPERSEDED', 'WITHDRAWN') THEN
              RAISE EXCEPTION 'released snapshot state cannot become mutable';
            END IF;
          END IF;
          IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER trg_ncpc_protect_released_snapshot
          BEFORE UPDATE OR DELETE ON publication_snapshots
          FOR EACH ROW EXECUTE FUNCTION ncpc_protect_released_snapshot();

        CREATE FUNCTION ncpc_protect_released_entry() RETURNS trigger AS $$
        DECLARE snapshot_state varchar;
        BEGIN
          SELECT state INTO snapshot_state FROM publication_snapshots
            WHERE id = COALESCE(NEW.snapshot_id, OLD.snapshot_id);
          IF snapshot_state IN ('PUBLISHED', 'SUPERSEDED', 'WITHDRAWN') THEN
            RAISE EXCEPTION 'released snapshot entries are immutable';
          END IF;
          IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER trg_ncpc_protect_released_entry
          BEFORE UPDATE OR DELETE ON publication_entries
          FOR EACH ROW EXECUTE FUNCTION ncpc_protect_released_entry();

        CREATE FUNCTION ncpc_audit_append_only() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION 'audit events are append-only';
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER trg_ncpc_audit_append_only
          BEFORE UPDATE OR DELETE ON audit_events
          FOR EACH ROW EXECUTE FUNCTION ncpc_audit_append_only();
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("DROP TRIGGER IF EXISTS trg_ncpc_audit_append_only ON audit_events")
        op.execute("DROP FUNCTION IF EXISTS ncpc_audit_append_only()")
        op.execute("DROP TRIGGER IF EXISTS trg_ncpc_protect_released_entry ON publication_entries")
        op.execute("DROP FUNCTION IF EXISTS ncpc_protect_released_entry()")
        op.execute("DROP TRIGGER IF EXISTS trg_ncpc_protect_released_snapshot ON publication_snapshots")
        op.execute("DROP FUNCTION IF EXISTS ncpc_protect_released_snapshot()")
    op.drop_table('identity_relationships')
    op.drop_index(op.f('ix_review_decisions_review_case_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_review_cases_submission_id'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_public_id'), table_name='review_cases')
    op.drop_table('review_cases')
    op.drop_index(op.f('ix_proposed_changes_submission_id'), table_name='proposed_changes')
    op.drop_table('proposed_changes')
    op.drop_index('uq_coverage_active_business_product', table_name='business_coverages', postgresql_where=sa.text('active IS TRUE'), sqlite_where=sa.text('active IS 1'))
    op.drop_index(op.f('ix_business_coverages_submission_id'), table_name='business_coverages')
    op.drop_index(op.f('ix_business_coverages_shop_id'), table_name='business_coverages')
    op.drop_index(op.f('ix_business_coverages_business_id'), table_name='business_coverages')
    op.drop_table('business_coverages')
    op.drop_index(op.f('ix_submissions_submitter_client_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_public_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_business_product_ref'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_business_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_publication_entries_snapshot_id'), table_name='publication_entries')
    op.drop_table('publication_entries')
    op.drop_index('uq_barcode_trusted_active', table_name='barcode_claims', postgresql_where=sa.text("state = 'VERIFIED_ACTIVE' AND active IS TRUE"), sqlite_where=sa.text("state = 'VERIFIED_ACTIVE' AND active IS 1"))
    op.drop_index(op.f('ix_barcode_claims_variant_id'), table_name='barcode_claims')
    op.drop_index(op.f('ix_barcode_claims_normalized_value'), table_name='barcode_claims')
    op.drop_index(op.f('ix_barcode_claims_conflict_group_id'), table_name='barcode_claims')
    op.drop_table('barcode_claims')
    op.drop_index(op.f('ix_aliases_normalized_text'), table_name='aliases')
    op.drop_table('aliases')
    op.drop_index(op.f('ix_variants_public_id'), table_name='variants')
    op.drop_index(op.f('ix_variants_product_id'), table_name='variants')
    op.drop_index(op.f('ix_variants_normalized_name'), table_name='variants')
    op.drop_table('variants')
    op.drop_index(op.f('ix_publication_snapshots_public_id'), table_name='publication_snapshots')
    op.drop_table('publication_snapshots')
    op.drop_index(op.f('ix_products_public_id'), table_name='products')
    op.drop_index(op.f('ix_products_normalized_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('id_sequences')
    op.drop_table('categories')
    op.drop_table('brands')
    op.drop_index(op.f('ix_api_clients_business_id'), table_name='api_clients')
    op.drop_table('api_clients')
    # ### end Alembic commands ###
